version: "3"
services:
  diversostockapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diversostockapp
    ports:
      - "8000:8000"
    volumes:
      - db_volumes:/diverso-stock-app/shares_broker/db
      - .:/diverso-stock-app

volumes:
  db_volumes: