# Generated by Django 4.1.6 on 2023-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ticker', models.CharField(max_length=50, null=True)),
                ('logo', models.CharField(blank=True, max_length=250, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
