# Generated by Django 4.1.6 on 2023-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='no_of_shares',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
