# Generated by Django 4.1.6 on 2023-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ucurrency',
            field=models.CharField(blank=True, default='USD', max_length=50, null=True),
        ),
    ]
