# Generated by Django 4.1.6 on 2023-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_ucurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ucurrency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
