# Generated by Django 4.1.6 on 2023-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_ucurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ucurrency',
            field=models.CharField(default='USD', max_length=50),
            preserve_default=False,
        ),
    ]
