# Generated by Django 4.1.6 on 2023-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_ucurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('status', '-activate_date')},
        ),
        migrations.AddField(
            model_name='profile',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
    ]
