# Generated by Django 4.1.6 on 2023-03-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_options_profile_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
