# Generated by Django 4.1.6 on 2023-03-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=7, null=True),
        ),
    ]
