# Generated by Django 4.1.6 on 2023-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_shares_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='price',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
    ]
