# Generated by Django 4.1.6 on 2023-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_price_shares_c_shares_d_shares_h_shares_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(blank=True, default=50000.0),
        ),
    ]
